services:
  - type: web
    name: xray-classifier
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./run.sh"
    envVars:
      - key: PORT
        value: 8000
